### ISSUE TITLE
Doc Link returns 404

### ISSUE THREAD

**Issue by sylviapossenauteradata** [cloudera/cdpcli#1]
Hi,

the link to the cdp cli cloudera documentation returns a 404: https://docs.cloudera.com/management-console/cloud/cli/topics/mc-cli-generating-an-api-access-key.html

**Comment by bbreak** [comment]
Hi Sylvia, 

Would it be possible for you to open a new Cloudera support case for this issue? Some of the documentation has moved. I want to make sure that we get you the documentation you need and clean up any dangling links pointing to the old locations. 

Thanks!

**Comment by sylviapossenauteradata** [comment]
Hi Ben,

yeah, I will.

Thanks
